apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  DB_HOST: "{{ .Values.env.DB_HOST }}"
  DB_PORT: "{{ .Values.env.DB_PORT }}"
  DB_NAME: "{{ .Values.env.DB_NAME }}"
