apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.env.DB_USER}}"
  DB_PASSWORD: "{{ .Values.env.DB_PASSWORD}}"
